### ISSUE TITLE
Video don’t loop

### ISSUE THREAD

**Issue by bado4** [Traurige/Eneko#12]
**Describe the bug:**
The video don’t loop 
**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version:15.1.1
- Device:13 pro
- Jailbreak:xina

**Comment by Traurige** [comment]
Please look for conflicts, such as Limneos tweaks.

**Comment by Traurige** [comment]
I will close this issue in two days, if no response is provided.
