### ISSUE TITLE
Screen freezes

### ISSUE THREAD

**Issue by lehai062** [Traurige/Eneko#13]
**Describe the bug:**

The screen freezes when closing the control center.
https://github.com/Traurige/Eneko/assets/136236669/aa947dae-d121-4cff-b1dd-c8bd9728d9e8

**Steps to reproduce the behavior:**

Open the control center and close it again.

**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version: 16.5
- Device: iPhone 8
- Jailbreak: palera1n

**Comment by Traurige** [comment]
The screen recording doesn't show anything related to freezes. The status bar animates just fine and the wallpaper is playing. I'll need more information. Aside from that, I don't have a jailbroken iOS 16 device.

**Comment by Traurige** [comment]
Closed due to inactivity.
