### ISSUE TITLE
Not compatible with VoiceChangee XS

### ISSUE THREAD

**Issue by xHookman** [Traurige/Eneko#14]
**Describe the bug:**
Wallpaper is applied for 4-5 seconds and disappear. I found that it's caused when the tweak VoiceChanger XS is installed but I don't understand why :/ Is it caused by the using of PreferencesLoader ?

**Steps to reproduce the behavior:**
Just install VoiceChanger XS (iOS 11 to 16) and respring.

**Crash log:**
I do not get log with Cr4shed, I don't know if there is another way?

**System information:**
- iOS version: 14.7.1
- Device: iPhone 11 Pro
- Jailbreak: Unc0ver

**Comment by Traurige** [comment]
This has been an issue ever since Eneko was released and it's not going to be looked into.
