### ISSUE TITLE
Import from Files

### ISSUE THREAD

**Issue by phamduyphat** [Traurige/Eneko#17]
**Describe the requested feature:**
Import from Files
Why: for some reason(possibly due to having 10000 photos in the photos app) wallpapers keep displaying unable to load items.
Affects astolfo and eneko :<
**System information:**
- iOS version:14.6
- Device:iPhone X
- Jailbreak:checkra1n

**Comment by Traurige** [comment]
Eneko itself is not responsible for the video picker – LibGcUniversal is. Picking from files is also not planned.
