### ISSUE TITLE
Eneko stops working after a few seconds

### ISSUE THREAD

**Issue by Inklingtex** [Traurige/Eneko#6]
**Describe the bug:**
Eneko stops working after a few seconds

**Steps to reproduce the behavior:**

**Crash log:**
Upload your log file to pastebin and paste the link here.

**System information:**
- iOS version: 15.3.1
- Device:
- Jailbreak: Fugu15

**Comment by Traurige** [comment]
Please go look in the subreddit for people experiencing the same issue for a solution.
