### ISSUE TITLE
Crash upon installing

### ISSUE THREAD

**Issue by Scxttie** [Traurige/Eneko#8]
**Describe the bug:**
After installing the .deb it goes straight to safe mode, you cannot edit it or anything.

**Steps to reproduce the behavior:**
Download it.

**Crash log:**
There isn't one. Cannot get one anyway.

**System information:**
- iOS version: 15.0
- Device: iPhone XS Max
- Jailbreak: Dopamine

**Comment by Traurige** [comment]
iOS logs crashes itself. Preferences > Privacy > Analytics … > Analytics. Share one of those.

Without a log there’s nothing I can do except tell you to check for conflicts.

**Comment by Scxttie** [comment]
I see bunches of analytics data. 
"aggregated.diskwrites_resource"
"AMDEngagementExtension"

**Comment by Traurige** [comment]
SpringBoard crashes and thus you need to look for a SpringBoard crash.

**Comment by jonahdecker** [comment]
> SpringBoard crashes and thus you need to look for a SpringBoard crash log.

I am having the same issue on my iPhone XS running iOS 15.0.1. 

Here's the SpringBoard crash log: 
`Incident Identifier: F480FBD2-69F2-4710-B3F6-DA47398B34C5
CrashReporter Key:   a87abc3474f7876402c15ea1917bd98425deb822
Hardware Model:      iPhone11,2
Process:             SpringBoard [5145]
Path:                /System/Library/CoreServices/SpringBoard.app/SpringBoard
Identifier:          com.apple.springboard
Version:             1.0 (50)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.apple.springboard [1994]

Date/Time:           2023-05-09 16:18:40.1366 -0500
Launch Time:         2023-05-09 16:18:39.3037 -0500
OS Version:          iPhone OS 15.0.1 (19A348)
Release Type:        User
Baseband Version:    4.00.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00200001db391870 -> 0x00000001db391870 (possible pointer authentication failure)
Exception Codes: 0x0000000000000001, 0x00200001db391870
VM Region Info: 0x1db391870 is in 0x1db391400-0x1db392f48;  bytes after start: 1136  bytes before end: 5847
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      __DATA                   1db390000-1db391400 [    5K] rw-/rw- SM=COW  ...ispatch.dylib
--->  __AUTH                   1db391400-1db392f48 [    7K] rw-/rw- SM=COW  ...oreFoundation
      __AUTH                   1db392f48-1db395628 [   10K] rw-/rw- SM=COW  .../CoreServices
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:



Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libobjc.A.dylib               	       0x199b415e0 0x199b40000 + 5600
1   Foundation                    	       0x182e7616c 0x182dcc000 + 696684
2   Eneko.dylib                   	       0x1053b32b0 0x1053ac000 + 29360
3   Eneko.dylib                   	       0x1053b1928 0x1053ac000 + 22824
4   dyld                          	       0x102a54794 0x102a4c000 + 34708
5   dyld                          	       0x102a88130 0x102a4c000 + 246064
6   dyld                          	       0x102a52490 0x102a4c000 + 25744
7   dyld                          	       0x102a51698 0x102a4c000 + 22168
8   dyld                          	       0x102a509f8 0x102a4c000 + 18936
9   dyld                          	       0x102a87cb8 0x102a4c000 + 244920
10  dyld                          	       0x102a5de68 0x102a4c000 + 73320
11  dyld                          	       0x102a5aa10 0x102a4c000 + 59920
12  dyld                          	       0x102a563c4 0x102a4c000 + 41924
13  dyld                          	       0x102a5c570 0x102a4c000 + 66928
14  dyld                          	       0x102a55b54 0x102a4c000 + 39764
15  systemhook.dylib              	       0x1029cad38 0x1029c4000 + 27960
16  libinjector.dylib             	       0x102a3babc 0x102a34000 + 31420
17  dyld                          	       0x102a54794 0x102a4c000 + 34708
18  dyld                          	       0x102a88364 0x102a4c000 + 246628
19  dyld                          	       0x102a52490 0x102a4c000 + 25744
20  dyld                          	       0x102a51698 0x102a4c000 + 22168
21  dyld                          	       0x102a509f8 0x102a4c000 + 18936
22  dyld                          	       0x102a5debc 0x102a4c000 + 73404
23  dyld                          	       0x102a5aa10 0x102a4c000 + 59920
24  dyld                          	       0x102a563c4 0x102a4c000 + 41924
25  dyld                          	       0x102a5c570 0x102a4c000 + 66928
26  dyld                          	       0x102a55b54 0x102a4c000 + 39764
27  systemhook.dylib              	       0x1029cad38 0x1029c4000 + 27960
28  systemhook.dylib              	       0x1029cb414 0x1029c4000 + 29716
29  dyld                          	       0x102a54794 0x102a4c000 + 34708
30  dyld                          	       0x102a88364 0x102a4c000 + 246628
31  dyld                          	       0x102a52490 0x102a4c000 + 25744
32  dyld                          	       0x102a51698 0x102a4c000 + 22168
33  dyld                          	       0x102a509f8 0x102a4c000 + 18936
34  dyld                          	       0x102a5debc 0x102a4c000 + 73404
35  dyld                          	       0x102a5aa10 0x102a4c000 + 59920
36  dyld                          	       0x102a563c4 0x102a4c000 + 41924
37  dyld                          	       0x102a5c570 0x102a4c000 + 66928
38  dyld                          	       0x102a7bd44 0x102a4c000 + 195908
39  dyld                          	       0x102a673ac 0x102a4c000 + 111532
40  dyld                          	       0x102a65a04 0x102a4c000 + 104964

Thread 1:
0   libsystem_pthread.dylib       	       0x1f1174f48 0x1f1174000 + 3912


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001053b4160   x1: 0x00000001cb7e1d93   x2: 0x00000001dbd4efa8   x3: 0x0000000000000000
    x4: 0x000000028060a040   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x00000001cb7e1000   x9: 0x0000000000000103  x10: 0x6ae10001053b4160  x11: 0x0000000016c3bca5
   x12: 0x0000000000000001  x13: 0x00000001db391860  x14: 0x0000000000000000  x15: 0x00200001db391860
   x16: 0x00200001db391860  x17: 0xaa417d0182e76118  x18: 0x0000000000000000  x19: 0x00000001053b4160
   x20: 0x0000000000000000  x21: 0x0000000280609fc0  x22: 0x00000001cb7e1d93  x23: 0x00000001053ac260
   x24: 0x00000001053ac380  x25: 0x000000016d45e280  x26: 0x00000001053ac470  x27: 0x0000000281d431e0
   x28: 0x0000000281d431b0   fp: 0x000000016d45df20   lr: 0x0000000182e7616c
    sp: 0x000000016d45dee0   pc: 0x0000000199b415e0 cpsr: 0x20000000
   far: 0x000000018182bac0  esr: 0x56000080  Address size fault

Binary Images:
       0x199b40000 -        0x199b79fff libobjc.A.dylib arm64e  <6d12ade560653900a6bc80677ccac819> /usr/lib/libobjc.A.dylib
       0x182dcc000 -        0x1830d0fff Foundation arm64e  <efbca2ff8b8c3227abbc154ba851d23c> /System/Library/Frameworks/Foundation.framework/Foundation
       0x1053ac000 -        0x1053b3fff Eneko.dylib arm64e  <06aaffee8bd93c60b124684be85150ed> /private/preboot/161B9130F4B9EEDA603074F0CC9C70FF0FBF909EF59419A01D5863E0886F89991FCC587E2997E9907841202200E976E3/jb-YQxS2I/procursus/usr/lib/TweakInject/Eneko.dylib
       0x102a4c000 -        0x102aa3fff dyld arm64e  <d48c31ee061f370ba6f78391a1b53ed8> /usr/lib/dyld
       0x1029c4000 -        0x1029cbfff systemhook.dylib arm64e  <781b1016b3d2342b84a77d3f44e1f370> /usr/lib/systemhook.dylib
       0x102a34000 -        0x102a3bfff libinjector.dylib arm64e  <5e17d7464bcc3356ad78321d55215bfc> /private/preboot/161B9130F4B9EEDA603074F0CC9C70FF0FBF909EF59419A01D5863E0886F89991FCC587E2997E9907841202200E976E3/jb-YQxS2I/procursus/usr/lib/ellekit/libinjector.dylib
       0x1f1174000 -        0x1f117ffff libsystem_pthread.dylib arm64e  <bc1ce0c6a9f2396b9afb623d3acd5881> /usr/lib/system/libsystem_pthread.dylib
               0x0 - 0xffffffffffffffff ??? unknown-arch  <00000000000000000000000000000000> ???

EOF`

**Comment by Traurige** [comment]
Perhaps I need to compile it with Xcode 12's tc instead of 11's. @Scxttie @jonahdecker if you add me on Discord I can try it with either one of you.

**Comment by jonahdecker** [comment]
Sure, happy to help. My Discord is Jonah#1572. I'm busy with college finals right now so I might be slow to respond, but I will test it for you.
